# Author: https://443eb9.dev
# Github: https://github.com/443eb9/screen_filter

# Modify this config file, the program will detect the change and
# restart automatically.

toggle = "ctrl+alt+c"
freeze = "ctrl+alt+f"
mode = "OklabGrayscale"  # Options: OklabGrayscale, LabGrayscale
launch_on_startup = true
refresh_rate = 0 # Option: <Any Positive Integer>, 0 if don't limit
